### ISSUE TITLE
Leaflet.js Map not showing.

### ISSUE THREAD

**Issue by Barking2TheMax** [Plymouth-University-BSc-Computing/soft165-practicals-Barking2TheMax#2]
The code seems to be right from the example but it just isn't showing the map at all.

**Comment by shirleyatkinson** [comment]
Can you give me a bit more information - such as which branch and which file I can see where you have the issue.

**Comment by Barking2TheMax** [comment]
It's under branch dev_Week2, file main.php

**Comment by Barking2TheMax** [comment]
Issue resolved. Apparently copy and pasting the original code from the Leaflet.js website solved it.
